### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by VeNoMouS** [VeNoMouS/cloudscraper#10]
@Mirio
Re https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/20

```
Hi,
On the new project do you have implemented the captcha solver (using external resources)?
Thanks,
```

I actually worked out what was causing alot of the reCAPTCHA, and implemented fixes in place :)

However.. regardless I am going to be adding in 3rd party anti-captcha into this project.

**Comment by pannal** [comment]
@VeNoMouS could you elaborate on what caused the reCAPTCHAs? Also, why do you explicitly create a cipherSuite adapter?

**Comment by VeNoMouS** [comment]
same thing :) you answered your own question :)

**Comment by pannal** [comment]
Oh? So they check for the SSL properties of the connection as well? Wow.

**Comment by VeNoMouS** [comment]
Yea, after much investigation the ciphers were the only thing left... further investigation and testing proved me right.

**Comment by pro-src** [comment]
It's actually a bit more complicated then how I imagine it appears. The only thing that is a known fact, at this point, is that many people were facing seemingly inexplicable occurrences of reCAPTCHA, observing differences between systems, etc., and the inclusion of one specific cipher consistently reproduced the problem. Whether or not you were affected is determined by many factors, namely CPU(determines default cipher suite list), python version(Refactors said list since openssl defaults are stupid/insecure), various package versions i.e. urllib3. It was first discovered on python 2.7 when the cryptography package was present on a system and automatically imported/used. In which case, you were only affected if using a cryptography version greater than 2.4.0. I had initially dismissed the issue entirely citing the conditions that were needed to reproduce it on my own system but this has been proven to be a problem to some unknown extent. This project is the only one that has been able to shed light on the issue and protect against it. Thanks @VeNoMouS :100:

**Comment by pro-src** [comment]
@pannal Regarding cipher lists: https://github.com/VeNoMouS/cloudscraper/issues/29#issuecomment-489593476

**Comment by VeNoMouS** [comment]
Closing for now , as I don't see this as an issue as we solved the reCaptcha issues, should this be a problem in future we will circle back around and introduce some 3rd party modules to battle this, if you wish to keep this open @pannal thats cool as well :)
