### ISSUE TITLE
brotli handling

### ISSUE THREAD

**Issue by pannal** [VeNoMouS/cloudscraper#12]
Hey,

As far as I could see from my first code-digging into the new project you're removing the brotli capabilities of a user-agent that normally supports brotli, when brotli is explicitly disabled.

Is that a good idea for CF? Wouldn't it make more sense to restrict user-agents to non-brotli-capable user-agents once brotli is disabled? (Which is [what I've been doing in the fork](https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/cfscrape/__init__.py#L60) of your older cfscrape project)

Thank you!

**Comment by pro-src** [comment]
You're welcome for those lists. :smiley: 

You know, the option is available so that if Brotli is unavailable or for optimization, you can opt out. CF doesn't care for the time being. Imagine that restricting the UA to very old UA's is more likely to get you flagged. All recent browsers support Brotli.

**Comment by pro-src** [comment]
@pannal Did that make sense? That you shouldn't use Windows XP as your UA just so the accept-encoding header matches properly when it's currently safe to do otherwise? But from CF's perspective what are the odds that a normal user is using XP in 2019? I haven't tested the XP theory, wouldn't try it in the first place since I want to blend in. So ultimately you're screwed either way and shouldn't explicitly disable Brotli. Removing the option entirely makes the most sense to me but old UA's isn't a better option.

**Comment by VeNoMouS** [comment]
Brotli is a feature you can disable in chrome...

![image](https://user-images.githubusercontent.com/597545/56990121-59853e80-6be8-11e9-8e3f-4fda5e5737dd.png)

It makes no sense for CF to reject on accept-encoding... hence why it works with it enabled or disabled.

**Comment by pannal** [comment]
Great explanation @pro-src @VeNoMouS, thank you!

**Comment by VeNoMouS** [comment]
Additionally... requests / urllib3 doesn't actually support brotli.. I actually added in decompression support.
