### ISSUE TITLE
Is there any way to hook the isRecaptchaChallenge function so I can do proxy setup only if needed?

### ISSUE THREAD

**Issue by fake-name** [VeNoMouS/cloudscraper#123]
Basically, I have code that will [automatically stand up a SOCKS5 proxy if needed](https://github.com/fake-name/WebRequest/blob/master/WebRequest/Captcha/SocksProxy.py). Right now, I use it for my own code, but frankly this project is maintained by someone other then me, and it's codebase is probably better then anything I'd write anyways. 

Basically, I probe a website, and if I have to, start the local proxy, solve ReCaptcha, and then kill the proxy. 

To use this with cloudscraper's captcha solver integration, I'd either have to start the proxy for every cloudflare-wrapped site, or catch cloudflare failures and do a complete retry.

So, basically, is there any way can add something like a user-provided callback that gets invoked somewhere around here: https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L184

Really, having captcha-solver setup and teardown callbacks would be super handy for the general case. Or you could integrate the code I've put together for internal proxying (it has UPnP hole punching too!). 

------

Since `is_reCaptcha_Challenge` is a `@staticmethod`, I can't easily patch into it with subclassing hijinks either. Since I don't know my local proxy port beforehand, I could set it up by subclassing and adding logic to `is_reCaptcha_Challenge`, but I can't reach the `self.proxy` member to make changes from there. 

-------

Oh, another annoying thing. right now, recaptcha causes a `RuntimeError()` to be raised. This is _super_ unspecific, and the only way I can catch specifically that error is to catch everything, and look at the stringification of the raised error, which unsusprisingly is going to be pretty damn brittle.  some subclassed exceptions that are more specific would also be quite nice.

**Comment by VeNoMouS** [comment]
WIP:

* Custom Exceptions have been placed for reCaptcha

**Comment by fake-name** [comment]
Neat!

**Comment by VeNoMouS** [comment]
Sorry just an update, I've been a busy with a bunch of stuff as of late, i havent had any more time to work on this, just letting you know I haven't forgotten you

**Comment by fake-name** [comment]
Thanks for the update, and it's not a pressing issue. I've got a functional workaround at the moment.

**Comment by VeNoMouS** [comment]
So an update on this....

while finishing this up... I noticed in my pytest my raised custom exceptions weren't being trapped... it actually turns out there is a bug in py3 for over 10 yrs in relation to abstract classes (ABC) and custom exceptions... 

While you can define them and it raises them, you actually have to trap them 
*ie:*
- `except Exception` rather than  ie `reCaptcha_exceptions.reCaptcha_Parameter_Error

This can replicated via the following..

```python
from abc import ABC
class MyException(Exception, ABC):
    pass

class OtherException(Exception):
    pass

MyException.register(OtherException)

try:
    raise OtherException
except MyException:
    print("Correct: Caught MyException")
except Exception:
    print("Wrong: Caught something else")
```

Which yields the result `Wrong: Caught something else`

References for this bug and the pending py3 "patch" which have been sitting idle for over 2 years are..

- https://bugs.python.org/issue33271
- https://bugs.python.org/issue12029
 
So.... in order to support custom exceptions in the dynamically loaded modules for reCaptcha and the interpreters... I will need to rethink / refactor how I go about the load / population methodology, perhaps I move away from using ABC and writing my own abstraction

**Comment by fake-name** [comment]
Whooo, interpreter bugs!

There's a similar issue I've run into where locks in the stdout aren't sanitized on fork(), so if you're multiprocessing a lot you can wind up with child processes where the stdout lock is held and never released. It *also* has a fix which has been idle for years.

**Comment by VeNoMouS** [comment]
Managed to work around this, its current in dev branch

**Comment by VeNoMouS** [comment]
There are several ways this can now be inspected, via post hooking for example or via the `perform_request`
