### ISSUE TITLE
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by dipu-bd** [VeNoMouS/cloudscraper#159]
While requesting to `https` sites, I am getting this error:

```
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```

I am getting over this issue by disabling `check_hostname` like this:

```
import cloudscraper

scrapper = cloudscraper.create_scraper()
scrapper.get_adapter('https://').ssl_context.check_hostname = False
```

But I guess this is not exactly the proper way to do it. How to resolve it properly?

**Comment by dipu-bd** [comment]
I passed `verify=False` with `scrapper.get()`. That was causing this issue.

**Comment by VeNoMouS** [comment]
This is because I use `ssl.Purpose.SERVER_AUTH` on the ssl context for the adapter... as you already discovered yourself.. which enables check_hostname.

Because... well **ALL** hosts on cloudflare are SSL verified... if they aren't.... something is seriously wrong!! 

But glad you worked it out yourself in an elegant solution, I haven't actually sett `get_adapter` before... so its nice to know that exists rather than explicitly calling the key..

```
scraper.adapters['https://'].ssl_context.check_hostname = False
```


;P
