### ISSUE TITLE
[Errno 24] Too many open files: /browsers.json

### ISSUE THREAD

**Issue by https-finesse** [VeNoMouS/cloudscraper#187]
Hi, I've been stress testing my script lately, and I've noticed that after 1/2 hours running, I receive this specific error, caused probably by opening many Cloudscraper scrapers.

` [Errno 24] Too many open files: '/path/cloudscraper/user_agent/browsers.json' `

Is there anything I can do to avoid this? I also tried to `.close()` the session every time i needed to create a new one but doesn't look like it helped somehow.

**Comment by VeNoMouS** [comment]
Each time an instance is created, browsers.json is opened and closed...

https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/__init__.py#L77-L81

It is not stored in memory purely because the foot print would be to large and its pointless..

I would suggest you increase your **File Descriptor** limit on your OS
