### ISSUE TITLE
Empty cf_clearance?

### ISSUE THREAD

**Issue by para-dise** [VeNoMouS/cloudscraper#33]
I just started using the lib, and I'm not fully sure, but it seems weird to me that the cf_clearance is empty.

My code:
```python
import cloudscraper

proxies = {"http": "http://x.x.x.x:xxxx", "https": "http://x.x.x.x:xxxx"}
tokens, user_agent = cloudscraper.get_tokens("https://spigotmc.org/", proxies=proxies)
print(tokens)
```

And this seemed to return this:
`{'cf_clearance': '', '__cfduid': 'd08aa4c08c1462447eb2ad1a390b4ec131557165306'}
`
Is this normal? I thought cloudflare sets a cf_clearance.

**Comment by VeNoMouS** [comment]
Hi @para-dise , while not normal , i have seen that happen once or twice... however... you only need the __cfduid in order to use cloudflare, so i wouldnt be too concerned about it.

is there any reason you're extracting the cookies rather than just using `cloudscraper.get()` or `.post()` etc, as the library is calling requests as a super.
