### ISSUE TITLE
Get captchas every time while on node js never

### ISSUE THREAD

**Issue by johnnyollo** [VeNoMouS/cloudscraper#37]
Hi, I'm new of python, I get captchas on every request while on node js with https://github.com/codemanki/cloudscraper never got one.
I tried to solve them with 3rd part services, but I have to solve dozens of captchas before be able to see the page. This happened on every cf site that I tried, no ip ban.

**Comment by VeNoMouS** [comment]
ok? not sure what you're asking me here?

**Comment by VeNoMouS** [comment]
@johnnyollo i just pushed 1.1.9 release can you test that and see if you still have issues,

sorry first time i read what you said, i didn't understand what you were saying, apologies.

**Comment by johnnyollo** [comment]
Thank you, I’ll try it as soon as I’ll be at home. Sorry for my English

**Comment by johnnyollo** [comment]
still get captchas,
my code: https://pastebin.com/QHhpjZSU
output: https://pastebin.com/DAEbr9xd

**Comment by VeNoMouS** [comment]
Is there any reason your setting custom headers? you have to have them in the exact order otherwise you will get a captcha ... the code sets a random browser user-agent for you from https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json so there is no need to specify a user-agent like that...

**Comment by VeNoMouS** [comment]
@johnnyollo , sorry did you get you're issue resolved?
