### ISSUE TITLE
Error "AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'"

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudscraper#58]
Hello,

Since the last update (1.26), I receive this error message on Japscan website:

```
Traceback (most recent call last):
  File "/home/maxx/bin/dl_scripts/mangas_dl_japscan.py", line 39, in <module>
    data = getPage().getpage_text(sys.argv[2])
  File "/home/maxx/bin/dl_scripts/CF_getPage_2.py", line 27, in getpage_text
    cf = cloudscraper.create_scraper()
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper/__init__.py", line 250, in create_scraper
    scraper = cls(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper/__init__.py", line 91, in __init__
    self.mount('https://', CipherSuiteAdapter(self.loadCipherSuite()))
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper/__init__.py", line 49, in __init__
    ssl_version=ssl.PROTOCOL_TLS,
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'
```

Do you know what could cause it ? 
It is weird as it seems I do not have this error on some computers.

Thank you!

**Comment by Krylanc3lo** [comment]
Downgrading to 1.1.20 helped on the server I was facing the issue

**Comment by VeNoMouS** [comment]
What version is your python, PROTOCOL_TLS should be defiened in __ssl.py__ 

@Krylanc3lo all the ciphers used atm are TLS 1.2 / 1.3... 

![image](https://user-images.githubusercontent.com/597545/60773095-434dae80-a154-11e9-9542-95c7e958449f.png)

I'll add a bandaid in for the older versions, I did have one in place earlier but i removed it because... well it shouldnt be required if your keeping your system up to date... but for keeps sake i'll add a fix in :) only cause i <3 you ;P

**Comment by Krylanc3lo** [comment]
I am so lucky! thanks man ;)
You are right (as usual) about python version. I used 3.5 -> I updated to 3.7 and it is working well ;)

**Comment by VeNoMouS** [comment]
__Release 1.1.28__ b3ccc0a13d5e258ce2dac564800c4007b9c1681d will address this issue for you.

**Comment by Krylanc3lo** [comment]
Everything working as a charm!
